### ISSUE TITLE
labelPadding property of VictoryAxis doesn't seem to work

### ISSUE THREAD

**Issue by ritchieking** [FormidableLabs/victory-chart#104]
Hey there - I've been working on an internal charting tool based on Victory and haven't had any luck positioning axis labels using the `labelPadding` property. Thought I might be doing it wrong, so I tried playing with the property in one of your sandboxes, but it didn't seem to do anything:

![labelpadding](https://cloud.githubusercontent.com/assets/2760121/13251052/debf01da-d9fb-11e5-8ca0-978568120eb5.gif)

**Comment by boygirl** [comment]
Hi @ritchieking, could you please reproduce this in a [jsbin](http://jsbin.com/vikiha/edit?html,js,output) or [jsFiddle](https://jsfiddle.net/5g20p8vd/) to remove any sources of error from our ecology docs? They're really handy, but not always perfect.

Thanks!

**Comment by neverfox** [comment]
@ritchieking Use `style={{ axisLabel: { padding: 10 }}`

**Comment by ritchieking** [comment]
worked like a charm - thanks, @neverfox!

**Comment by neverfox** [comment]
Great! That said, a quick skim of the source does seem to indicate that `labelPadding` may be vestigial at this point.

**Comment by boygirl** [comment]
Vestigial `labelPadding` prop removed in `victory-chart@6.0.0`
