### ISSUE TITLE
Add API for getting chart measurements

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory-chart#107]
- width and gutters of bars
- etc

This is driven by this use case of aligning a table with a bar chart:
![chart-aligned-table](https://cloud.githubusercontent.com/assets/794843/13268147/aecef464-da35-11e5-93e5-84c920a6693b.png)

**Comment by coopy** [comment]
Possible alternate solution: Have the external component pass constraints to the chart.

**Comment by boygirl** [comment]
Closing: no longer necessary with constraint based layouts
