### ISSUE TITLE
label padding is off when values are negative

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-chart#124]
_From @boygirl on December 14, 2015 5:12_

labels are too close to bars for negative bars both horizontal and vertical

_Copied from original issue: FormidableLabs/victory-bar#63_

**Comment by boygirl** [comment]
_From @coopy on January 20, 2016 21:29_

We need a holistic label solution - wait for `Radium.Typography`

**Comment by boygirl** [comment]
Needs repro

**Comment by ebrillhart** [comment]
Are we trying to integrate Radium.Typography or just come up with a from-scratch solution?

**Comment by boygirl** [comment]
@ebrillhart please come up with a from scratch solution. This should only need to be a minor adjustment

**Comment by ebrillhart** [comment]
fixed with #256
