### ISSUE TITLE
Warn the user when both x and samples are given as props

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-chart#125]
_From @boygirl on October 29, 2015 4:29_

users might be confused in a situation like:

```
<VictoryLine x={[1, 2, 3]}, y={(x) => Math.sin(x)} samples={50}/>
```
when only 3 points are plotted (corresponding to the 3 `x` values)

_Copied from original issue: FormidableLabs/victory-line#20_

**Comment by josectello** [comment]
@boygirl I had an idea I wanted to run by you before submitting any PR. Perhaps in the `samples` prop declared in `propTypes`, we can assign a function with a single line if-statement checking if `x` is defined or not when a user is building a component:

```
samples: function(props, propName, componentName) {
  if (props.x != undefined) return new Error('The "samples" prop is overridden when the "x" prop of a component is passed value(s).')
}
```
This would log the error in the console if `x` is used in conjunction with `samples`. However, I am a bit stumped as how to maintain the value for `samples` as a non-negative value (and use a function), which is currently what the `samples` prop is set to in several of the victory files:

```
samples: CustomPropTypes.nonNegative,
```

**Comment by boygirl** [comment]
@josectello thanks for your help again! The pattern we are using the moment is just to use `Log.warn` for situations like this one that don't actually prevent a chart from rendering. https://github.com/FormidableLabs/victory-chart/blob/master/src/components/victory-chart/helper-methods.js#L34

`Log` here is just a little utility exported by `VictoryCore`.

**Comment by josectello** [comment]
Thanks for the input @boygirl. Hopefully, I'll have a PR up later this week once I make sure I'm not breaking any tests :)

**Comment by josectello** [comment]
Hey @boygirl, I've submitted a PR but I apologize in advance if the PR is not fully polished; I am in the process of adjusting it, but was wondering if it were possible to receive some feedback?
