### ISSUE TITLE
data sorting should be optional for victory-line

### ISSUE THREAD

**Issue by jmaguirrei** [FormidableLabs/victory-chart#130]
Hello @boygirl , if you try to draw a polygon, let's say a rectangle:

```
 <VictoryLine
    data={[
      {x: 0, y: 0},
      {x: 5, y: 0},
      {x: 5, y: 2},      
      {x: 0, y: 2}
    ]}
 />
```
(paste in)
http://victory.formidable.com/docs/victory-line

![victoryline](https://cloud.githubusercontent.com/assets/11958637/13443652/c0f4f00c-dfe0-11e5-9f0d-ab13c502dcb0.png)

It seems you can't "go back" in the X axis... But any SVG path allows you to move from point to point in any direction.

I moved this issue from VictoryLine, because it's deprecated.

I dont know how VictoryArea will be implemented, but my question refers not only to draw a polygon, but to draw any path with Victory, like in d3 or plain SVG, you can define a line that go from one point to another in any direction, following a path that can be linear, basis or other kind of interpolations.

If you think that a line could exits not only in the context of a chart, but in te context of a "shape", then you must consider leave VictoryLine as a independent module, just a thought...

**Comment by dandelany** [comment]
This is a good point - another way to think of it is that the current implementation only lets you plot functions of the general form `y = f(x)` (ie. one-to-one, one Y value for each X-value), whereas it would be nice to also be able to use the X-axis as the dependent axis (`x = f(y)`) or to plot generalized parametric curves which "loop back on themselves" in XY-space.

**Comment by jmaguirrei** [comment]
If you know the {x,y} of an array of points, and the order matters, you could draw something like this with one react-victory component:

![test8](https://cloud.githubusercontent.com/assets/11958637/13445128/3bebda8e-dfe9-11e5-8501-fb42dd1dfe72.JPG)

This is an standard SVG path element, I think less complex than any other Victory chart.
And very useful if your goal is to draw shapes base on data, not only present data as a chart.

**Comment by boygirl** [comment]
@jmaguirrei we're currently sorting the datasets on the x value for victory line because we were getting so off looking charts, but that behavior could be removed. The trade off is just less hand-holding, and moving the responsibility for data ordering to the user.

**Comment by jmaguirrei** [comment]
@boygirl I understand, maybe the sorting should be the default, but the user can specify a property `sortX = {false}` or something like that, to have a "free" path available.
This could be a request?

**Comment by boygirl** [comment]
@jmaguirrei works for me

**Comment by jmaguirrei** [comment]
Thanks!

**Comment by boygirl** [comment]
closing in favor of https://github.com/FormidableLabs/victory/issues/254
