### ISSUE TITLE
Round decimals on SVG elements

### ISSUE THREAD

**Issue by jmaguirrei** [FormidableLabs/victory-chart#131]
Hello

I generated a VictoryLine (with `interpolation = 'basis'`) and this is the result:

`<path style="stroke-width:2;fill:none;stroke:#756f6a;opacity:1;" d="M50,30L50,33.333333333333336C50,36.666666666666664,50,43.333333333333336,56.666666666666664,46.666666666666664C63.333333333333336,50,76.66666666666667,50,83.33333333333333,46.666666666666664C90,43.333333333333336,90,36.666666666666664,90,33.333333333333336L90,30" data-reactid=".0.3.0.0.1.1.0.0.$=10=2$line-segment-0"></path>`

Is it possible to the user to specify the number of decimals he needs? For example with 2 decimals

`<path style="stroke-width:2;fill:none;stroke:#756f6a;opacity:1;" d="M50,30L50,33.33C50,36.67,50,43.33,56.67,46.67C63.33,50,76.67,50,83.33,46.67C90,43.33,90,36.67,90,33.33L90,30" data-reactid=".0.3.0.0.1.1.0.0.$=10=2$line-segment-0"></path>`

The new element looks exactly the same and it's almost 50% less "data" (maybe and better performant?)

Thanks

**Comment by boygirl** [comment]
@jmaguirrei we're using `d3-shape` to generate these paths, and an option to set the data precision is not exposed. I think manually truncating the data would be _less_ performant, so this is not an option for victory-line or victory-area. It would technically be possible for victory-bar and victory-scatter where we are building our own paths, but I am dubious that the performance improvement would be noticeable enough to warrant expanding the api surface.

**Comment by jmaguirrei** [comment]
@boygirl Today, I will be trying to meet the same I already have with d3, which are no charts but some drawings (an office layout), with pure svg elements within react. I realised native svg plays nicely within react and almost have what I need out of the box (just need to hack some d3 functions to interpolate lines).

**Comment by divmain** [comment]
Looks like it would be possible to truncate the path values, if that's a worthwhile feature.  In D3 parlance:

```javascript
var data = [342.342634624, 25.3123, 120.246347];

var truncate = d3.format(".2f");
var getPath = d3.svg.line()
  .x(function (d, i) { return i * 80; })
  .y(function (d) { return truncate(d); });

var svg = d3.select("svg")
  .attr("height", 400)
  .attr("width", 400)
  .append("path")
    .attr("d", getPath(data))
    .attr("fill", "none")
    .attr("stroke-width", 4)
    .style("stroke", "red");
```

Which renders:
```svg
<svg height="400" width="400">
  <path
    d="M0,342.34L80,25.31L160,120.25"
    fill="none"
    stroke-width="4"
    style="stroke: red;"
  ></path>
</svg>
```

As a generic solution, we could take an optional `yTransform` prop (or a better name), which all y-values would be passed through before being passed to `d3-shape` functions.  Then @jmaguirrei or whomever else could provide `yTransform: d3.format(".2f")`.

**Comment by dandelany** [comment]
It would have to be named much more specifically, like `yPathDatumTransform` or something. I'm inclined to agree with @boygirl here - this seems like an awkward expansion of the API surface for *very* minimal benefit.

**Comment by divmain** [comment]
Agreed, this is definitely an edge case.  However, I could see merit in cases where SVG data were being server-side rendered.  For large SVGs, abundant and non-repeating strings like this will be difficult to compress and can significantly bloat output size.
