### ISSUE TITLE
Development docs wont build

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-chart#134]
on latest master with a fresh `npm install` the command `builder run docs-dev` results in 
```
ERROR in multi app
Module not found: Error: Cannot resolve module 'babel-loader' in /Users/boygirl/formidable/v/victory-chart
 @ multi app
```

Can anyone reproduce this?

**Comment by coopy** [comment]
I can't reproduce this. `npm -v`, `node -v`? do you have webpack installed globally perchance? `npm uninstall -g webpack`

**Comment by boygirl** [comment]
Yes, that put the magic dust back in. Sorry about that.

**Comment by coopy** [comment]
Yay, glad that was it!
