### ISSUE TITLE
Feature request: PNG export

### ISSUE THREAD

**Issue by rbvea** [FormidableLabs/victory-chart#137]
Would be nice to have some built-in way to export a png of a victory chart.  I've used [Fabric.js](http://fabricjs.com/) in the past to export svg's so that might be a way to do it...

**Comment by bosung90** [comment]
Would be nice to also have export support for pdf

**Comment by boygirl** [comment]
PNG export is supported in [victory-cli](https://github.com/FormidableLabs/victory-cli)
