### ISSUE TITLE
<VictoryBar stacked /> default data is not in the right format. 

### ISSUE THREAD

**Issue by janusch** [FormidableLabs/victory-chart#143]
Nothing drastic, though worth mentioning. The default data of the `<VictoryBar stacked />` graph does not produce a stacked chart.

It should be of this format: `[
                    [
                      {x: 1, y: 1},
                      {x: 2, y: 2},
                      {x: 3, y: 3}
                    ],
                    [
                      {x: 1, y: 2},
                      {x: 2, y: 1},
                      {x: 3, y: 1}
                    ],
                    [
                      {x: 1, y: 3},
                      {x: 2, y: 4},
                      {x: 3, y: 2}
                    ],
                ]`

and is instead of this format: `[
    {x: 1, y: 1},
    {x: 2, y: 2},
    {x: 3, y: 3},
    {x: 4, y: 2},
    {x: 5, y: 1}
  ]`

**Comment by boygirl** [comment]
no longer relevant with new `VictoryStack` wrapper
