### ISSUE TITLE
Setting `orientation="right"` for dependetAxis inverts X domain

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-chart#148]
_From @okonet on March 9, 2016 15:12_

Execute following code on http://victory.formidable.com/docs/victory-chart

```jsx
<VictoryChart>
 <VictoryAxis
  scale="time"
  tickValues={[
    new Date(1980, 1, 1),
    new Date(1990, 1, 1),
    new Date(2000, 1, 1),
    new Date(2010, 1, 1),
    new Date(2020, 1, 1)]}
    tickFormat={(x) => x.getFullYear()}/>
    
  <VictoryAxis 
  	dependentAxis
    orientation="right"
    padding={75}
    label="y-axis"
    standalone={false}/>
</VictoryChart>
```
Actual orientation of X axis:
![2016-03-09 at 16 11](https://cloud.githubusercontent.com/assets/11071/13639562/9a134362-e611-11e5-82ee-e6591ec8c4d2.png)

Expected orientation of X axis:
![2016-03-09 at 16 11](https://cloud.githubusercontent.com/assets/11071/13639575/a52e294c-e611-11e5-9258-92d60b2e7ff7.png)

_Copied from original issue: FormidableLabs/victory-axis#82_

**Comment by boygirl** [comment]
I can't decide whether this is a bug or a desired behavior.

**Comment by okonet** [comment]
That's implicit behavior and there's no way to change it ATM so to me that's a bug. I'd suggest to add `orientation` to horizontal axis as well. 

Also I believe last time I checked it was gone.
