### ISSUE TITLE
markers and labels for individual data points in VictoryLine and VictoryArea

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-chart#164]
line and area should have makers (invisible by default) and the option of labels on individual data points. Markers (invisible or otherwise) would be a more reasonable place to attach events than on the line itself.

**Comment by cpb** [comment]
I'm going to take a stab at the markers for individual data points as the demo example for FormidableLabs/victory-chart#166 (adds dataComponent prop to Line)

**Comment by boygirl** [comment]
Cat demo is so good! Approved!

**Comment by boygirl** [comment]
On second thought, all of this functionality already exists in VictoryScatter, and can be easily composed with VictoryLine or VictoryArea.
