### ISSUE TITLE
Upgrade `d3-scale` dependency

### ISSUE THREAD

**Issue by globexdesigns** [FormidableLabs/victory-chart#178]
victory-chart is using a very old version of the `d3-scale` npm package. The current version used is `0.2.0`, but the latest available is `0.6.4`.

This results in the following warning when installing victory:

```
npm WARN deprecated d3-arrays@0.4.1: Renamed d3-array (singular).
```

Any reason this dependency can't be upgraded?

**Comment by boygirl** [comment]
@globexdesigns Yep, absolutely. I'll make sure this is done for the next release.

**Comment by globexdesigns** [comment]
Thanks for the super fast turnaround. You guys are doing an awesome job with victory. Can't wait until we can share with you the apps we're building with it :)
