### ISSUE TITLE
Support for Two Dependent Axes (Dual Y-Axis Chart)

### ISSUE THREAD

**Issue by joshburgess** [FormidableLabs/victory-chart#185]
Is it possible to have two y-axes on a single chart (using different scales & representing different metrics) at the moment?

**Comment by boygirl** [comment]
Not when using the `VictoryChart` wrapper, but you can absolutely compose a chart manually with several axes. It's a bit of manual work to keep the layout correct. This example is a little out of data with recent changes to the API, but it should give you a general idea of how to go about that: https://github.com/FormidableLabs/victory-examples/blob/master/demo/app.jsx
