### ISSUE TITLE
VictoryGroup: props.children.every is not a function 

### ISSUE THREAD

**Issue by ApolloTang** [FormidableLabs/victory-chart#201]
I am tyring to reproduce Fig.8 in: 

http://formidable.com/open-source/victory/docs/victory-chart

here is my repo: 

https://github.com/ApolloTang/n-victory/blob/master/04-lab3/app/05-animation-demo2/index.js

but it crash at : 
getCalculatedProps() in
victory-chart/src/components/victory-group/victory-group.js

```
  getCalculatedProps(props, childComponents, style) {
    const horizontal = props.horizontal || props.children.every(
      (component) => component.props.horizontal
    );
```
<img width="865" alt="screen shot 2016-05-08 at 12 23 38 pm" src="https://cloud.githubusercontent.com/assets/1150961/15098973/240f2baa-1518-11e6-8969-917e7b15b449.png">

I am not sure but I think that is because every() is supposed to delegate to lodash _.every() ? 

```
getCalculatedProps(props, childComponents, style) {
    const horizontal = props.horizontal || _.every( props.children,
      (child) => _.get(child, `props.horizontal`, false)
    );
```

Could you verify this please ?  Thanks so much

**Comment by boygirl** [comment]
@ApolloTang I believe this is an issue because victory-group is expecting more than one child component, and I have failed to check on that edge case. With multiple children (or no group wrapper) the chart renders without error.

**Comment by ApolloTang** [comment]
@boygirl Thanks, I'll try that.
