### ISSUE TITLE
Events on the chart itself

### ISSUE THREAD

**Issue by tquetano-r7** [FormidableLabs/victory-chart#204]
I've been scouring the docs and can't find this, so if it's somewhere I do apologize.

I'm trying to put event listeners on the chart itself (not its data elements). For test purposes I was using onMouseEnter, and applying it directly to the chart does not work:
```
<VictoryPie
  onMouseEnter={(e) => {
    console.log(e.currentTarget);
  }}
/>
```
In the `events` prop I see things related to both `data` and `labels` (and have used them successfully), but no mention of a third option (such as `chart`). What is the correct way to access the event listeners for the chart itself?

**Comment by boygirl** [comment]
Hi there, sorry this isn't clear in the docs. To put an event on the entire svg for something like VictoryPie the namespace you should use is parent like in the style prop.
