### ISSUE TITLE
Victory events returning datum breaks VictoryBar position

### ISSUE THREAD

**Issue by stephenotalora** [FormidableLabs/victory-chart#205]
While handling events if one return datum `VictoryChart` stops updating the Bar datum and bar position goes out of sync with the current domain.

See: https://jsfiddle.net/stephenota/mkLnqepx/43/ as a simple example of the current `victory@0.6.1` behavior.

**Comment by boygirl** [comment]
After looking at your fiddle, I think what's going on is the argument you're calling `datum` is actually all of the props that control an individual bar component. By returning those from your event handler, you're storing them on state for that particular bar. So when the bar updates it is also assigning whatever props you've stored on state. This lets you do cool stuff like highlight a bar, and keep that styling while it animates to a new position, etc. But in this case all the props the bar had at the time of the event handler being called are assigned again, so the bar will never update at all.
