### ISSUE TITLE
[Victory-Axis] tickCount prop explanation?

### ISSUE THREAD

**Issue by hasSean** [FormidableLabs/victory-chart#206]
Could someone familiar with this library explain how the tickCount prop is supposed to work? The description says...

> The tickCount prop specifies how many ticks should be drawn on the axis if tickValues are not explicitly provided.

...but that doesn't seem to be always true. It seems like I am getting a number of ticks that's based off of some calculation of my desired number of ticks vs the scale of my data. Here are images that hopefully can illustrate my point. 

a tickCount of 2 or 3 gives me 3 ticks:
![image](https://cloud.githubusercontent.com/assets/12942422/15199613/aaecf872-1794-11e6-8b9e-216fec306179.png)

a tickCount of 4, 5, 6 or 7 gives me 6 ticks:
![image](https://cloud.githubusercontent.com/assets/12942422/15199734/adaa8c2c-1795-11e6-820f-d0ddb3cd6443.png)
 
and a tickCount of 8 to 15 gives me 11 ticks:
![image](https://cloud.githubusercontent.com/assets/12942422/15199780/fad085ba-1795-11e6-85f3-c32c32282741.png)

I'm currently working on something a little more complicated than the examples above, but am unable to get my desired result of 6 ticks. I can only get 3 or 7 depending on which number is closer to the tickCount I specify: 
![image](https://cloud.githubusercontent.com/assets/12942422/15199835/646dc6c2-1796-11e6-84a7-cf83a2240a27.png)

Is the solution for now just to figure out my own desired tickValues based on the max y-value in my dataset and then pass those into the tickValues prop instead of trying to use the tickCount prop?

Thanks for any insight you can provide :)

**Comment by dandelany** [comment]
@hasSean this is intended behavior, see the [docs for d3.scale.ticks](https://github.com/mbostock/d3/wiki/Quantitative-Scales#linear_ticks), which tickCount uses internally. "The specified count is only a hint; the scale may return more or fewer values depending on the input domain." - because it prioritizes human-friendliness over getting the exact # of ticks you requested. So yes, you should pass custom tick values if you want ultimate control over them.

**Comment by boygirl** [comment]
@hasSean the `tickCount` prop is based on https://github.com/mbostock/d3/wiki/Quantitative-Scales#linear_ticks. This method in d3 places priority on returning evenly spaced ticks, but doesn't guarantee an exact number, only an approximate. I will dig in and see if I can modify that method, or at minimum update the docs with the next release.

**Comment by boygirl** [comment]
ha! thanks @dandelany

**Comment by dandelany** [comment]
haha ;)
