### ISSUE TITLE
BUG: incorrect axis date formatting. Sundays appear as months

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-chart#219]
@alikhani provided the following fiddle in which Sundays are being misrepresented as "Jun". Is this something in Victory, or is this a bug in d3-scale default tick formatting for time scales?
https://jsfiddle.net/alikhani/t9s1ycx1/5/

**Comment by awesomebob** [comment]
Here's another fun example: https://jsfiddle.net/AwesomeBob/6fyfs28p/1/ with the sequence

    [Thu 31, 2016, Sat 02, Jan 03, Mon 04]

I found that this is in fact the default setting for d3.time.scale.

"The tick format provided by d3.time.scale is a multi-scale tick format, meaning that it formats times differently depending on the time." found on [this example](http://bl.ocks.org/mbostock/4149176)

The d3 docs explains how to [define your own multi-scale tick format](https://github.com/d3/d3/wiki/Time-Formatting#format_multi)

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory#352
