### ISSUE TITLE
candlestick chart component

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-chart#223]
Create a VictoryCandlestick component for use with VictoryChart

similar to this example: http://bl.ocks.org/abeppu/1074045

The main difference between VictoryCandlestick and other components is that it will have 4 values corresponding to the y-axis per datum (high, low, close, open).

The following methods will be complicated by this change:

- getDomain: will need to take the min / max of all four y values into account when calculating the y domain

- getData: v1 can require a strict data format (i.e. an array of objects that must have x, high, low, close, and open as properties) but v2 should support data accessors for these values as in the other components. The accessors for these values will also need to validate that only numerical values are given.

- getStyles: color is meaningful in candlestick charts, so the fill of the data component will be determined by a separate prop rather than by the style object. Maybe something like:
```
candleColors: PropTypes.shape({
  positive: PropTypes.string,
  negative: PropTypes.string
})
```

**Comment by ebrillhart** [comment]
closed with #239
