### ISSUE TITLE
VictoryChart wrapper component only provides react synthetic event and no further information regarding the scale or domain of the chart

### ISSUE THREAD

**Issue by stephenotalora** [FormidableLabs/victory-chart#230]
Unlike the more specialized components `VictoryBar` `VictoryLine` etc. `VictoryChart` does not pass any information regarding the scale and/or domain coordinates of the chart in the event handler object pass to `VictoryChart` `events` prop other than just the original React synthetic event. 

Since `VictoryChart` is the wrapper for all other victory components instead of having to do a mouse over on a path element or for example a victory-bar, I believe that a mouse over anywhere in the area of the chart should also be passed as information to the event handlers of this component. 

VictoryChart `events` prop information pass with the callback: 
![screen shot 2016-06-01 at 5 57 41 pm](https://cloud.githubusercontent.com/assets/6519974/15730555/8cbb94e6-2822-11e6-8bf3-ea0a66821da7.png)

VictoryBar `events` prop info pass with the callback: 
![screen shot 2016-06-01 at 5 58 27 pm](https://cloud.githubusercontent.com/assets/6519974/15730567/a853739a-2822-11e6-8e9a-54bd124fd657.png)

**Comment by boygirl** [comment]
@stephenotalora this will be released tomorrow! 

Relevant PRs
https://github.com/FormidableLabs/victory-chart/pull/252
https://github.com/FormidableLabs/victory-chart/issues/245
https://github.com/FormidableLabs/victory-core/pull/70
