### ISSUE TITLE
VictoryLine broken after `victory@0.6.1`

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-chart#241]
Only shows up in `dist`

https://jsfiddle.net/0Lvet4ud/

corresponds to `victory-chart@8.0.0` and introduction of `LodashModuleReplacementPlugin` in `builder-victory-component`

**Comment by ryan-roemer** [comment]
Seems like a great opportunity for a regression test as we also do the fix...

**Comment by boygirl** [comment]
I'm having a tough time with this one though since I cant reproduce it in dev at all.

**Comment by boygirl** [comment]
fixed by https://github.com/FormidableLabs/builder-victory-component/pull/64 and will be released on Friday 6/17
