### ISSUE TITLE
Pie chart slices overlap labels

### ISSUE THREAD

**Issue by DawidLoubser** [FormidableLabs/victory-chart#245]
Hi there,

For a simple `PieChart` rendered with the following settings:

~~~~
<VictoryPie
        style={{
            labels : {
                fontSize : 14,
                zIndex : 1000
            }
        }}
        animate={{
            duration : 500,
            onEnter : {
                before : a => a,
                after : a => a
            }
        }}
        data={[... omitted...]}
        />
~~~~

The pie slices seem to overlap the labels. Is there anything I can do to prevent this?

![pie-label-overlap](https://cloud.githubusercontent.com/assets/506878/16046904/500fa8c6-324e-11e6-8c8c-59f6ff9f6e03.png)

**Comment by boygirl** [comment]
@DawidLoubser Victory renders svg, so unfortunately we have poor z-index control. Currently the slices and labels are rendered in the same loop, which means later slices can be rendered "over" earlier ones. You could angle your labels, or reorder your data so that the slice that is getting cut off comes last in the set. I'm looking into better solutions for z-index like control. If nothing comes of it, I will move to rendering the labels in their own loop _after_ all the slices have been rendered. It will be a slight perf hit though.

**Comment by DawidLoubser** [comment]
Rendering the labels in their own loop was my first thought also - I don't think the average pie chart will have enough slices for the performance hit to be significant - such a chart wouldn't be readable in anyway!

This is actually quite a problem for a current project of mine - if you could find the time to do this it would be fantastic, otherwise I'll try to make some time and send a pull request with a fix...

thanks for a wonderful library, BTW - excited to see where it goes as further components are added to the basic set already there!

**Comment by boygirl** [comment]
Thanks! You have a fair point that the loops probably wont get out of hand in the pie repo. I can implement this here before our release on Friday. I do want to figure out a better way though. Having a separate loop for VictoryScatter for instance might get rough when there are lots of points.

**Comment by DawidLoubser** [comment]
If you could find the time to incorporate a change to two separate rendering loops for the Pie chart before your Friday release you'd be my hero!

Happy to collaborate therafter to try to find a better way in general. Though the painter's drawing model of SVG doesn't leave too many options - and I think accidental label overlap won't be a visual problem with `VictoryScatter` in the same way that it is with `VictoryPie` with it's big, label-stomping slices :-)

**Comment by boygirl** [comment]
@DawidLoubser I got it in! `victory@0.9.0` is published with this fix.
