### ISSUE TITLE
reusable Axis component

### ISSUE THREAD

**Issue by itajaja** [FormidableLabs/victory-chart#255]
if I want to write a custom Axis Component, I woul'd usually do something like this (this is a simplified example):

```js
// victory requires axis to be a function
/* eslint-disable react/prefer-stateless-function */
class RunChartAxis extends React.Component {
/* eslint-enable */
  render() {
    return (
      <VictoryAxis {...this.props} style={{ axis: { stroke: 'black' } }} />
    );
  }
}
```

This doesn't quite work, because

> Warning: Failed propType: `scale` in `VictoryAxis` must be a d3 scale. Check the render method of `RunChartAxis`

the result is that the Axis is not displayed as I would expect in many regards.

What is the best way to extend the base VictoryAxis component?

**Comment by boygirl** [comment]
@itajaja what you've done above should work unless `{...this.props}` is including a scale prop of its own, since `VictoryAxis` has a default scale prop. If you want to extend though, you might try something like 
```
import { VictoryAxis } from "victory-axis/src";

export default class extends VictoryAxis {
  
  render() {
    ...
  }
}
```

**Comment by itajaja** [comment]
I wasn't passing a scale prop. It's weird, I thought it's because probably the chart looks for a VictoryAxis component specifically. I'll try subclassing Victory Axis, even if that comes with drawbacks (eg react linting works only React.Component classes)

**Comment by boygirl** [comment]
Ah, you are using this within chart. Gotcha. VictoryChart does recursively check for `VictoryAxis` child components (`victory-chart@9.0.0` and above, `victory@0.8.0` and above)

In this case you must be sure that whatever component you are wrapping `VictoryAxis` in will pass down the props it receives from `VictoryChart` to `VictoryAxis`

**Comment by itajaja** [comment]
I see :) Isn't there a way to tell Chart which components are axes, so that Chart will know that it has to pass the axis props to them?

**Comment by boygirl** [comment]
Chart does know which components contain axes, but it passes the props to the parents in case you want to modify them before rendering the axis
