### ISSUE TITLE
Force layout chart

### ISSUE THREAD

**Issue by nfcampos** [FormidableLabs/victory-chart#276]
Hi,

I'm using `victory` in one project for most charts and I had the need for a force layout chart, which I've implemented. If you guys are interested in having a force layout chart as part of `victory` I can open a pull request. if yes, I have some questions before proceeding, regarding the API for the component, since working with the simulation + the several available forces in `d3-force` makes it a but different from all the other chart types with a `data` array.

Thanks,
Nuno

**Comment by boygirl** [comment]
@nfcampos That sounds great. We haven't had any full components authored by folks outside our org yet so there are a couple things to get ironed out. Are you in the gitter channel https://gitter.im/FormidableLabs/victory? Let's chat directly about getting this set up.

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory#349
