### ISSUE TITLE
Bug: Chart not loading on RN0.27.2

### ISSUE THREAD

**Issue by cablegunmaster** [FormidableLabs/victory-chart#278]
**Whats happening?** 
I get a big red error on my screen and kinda not want it there ;).
```
-Development server returns response 500.

Body: Transform error: /home/user/Development/project/node_modules/victory/lib/index.js:
[BABEL] /home/user/Development/project/node_modules/victory/lib/index.js: couldn't resolve extends clause of node_modules/builder-victory-component/config/babel/.babelrc in /home/user/Development/project/node_modules/victory.babelrc
type:  TransformError
```

**How to reproduce?**
- npm install victory
```
import { VictoryPie } from "victory"; 
``` 
Add the import to a file.
See a big fat error.

Dependencies installed which might have anything to do with issue.
```
    "babel-jest": "^9.0.0",
    "babel-preset-react-native": "^1.8.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "react": "15.1.0",
    "react-native": "0.27.2",
    "react-native-chart": "^0.1.14",
    "victory": "^0.9.0"
  },
```
Exact library: 0.9.2 victory chart.

My own babel.rc
```
{
  "presets": ["react-native-stage-0"]
}
```

Hopefully there is a small fix but I have no idea how to bughunt this on react-native any help is appreciated! 

Others also seen this issue and its related to:
.babelrc file with the extend part but no idea why its breaking and how to change it to work.

@vakhtang suggested to remove ' ./ ' in front but it didn't seem to work.
```
{
  "extends": "./node_modules/builder-victory-component/config/babel/.babelrc"
}
```

**Comment by cablegunmaster** [comment]
Bugfix: Renaming all the .babelrc in the different packages to something like .babelrcOLD seems to work.
Temporary fix? 
This might not what you want. 
still put this open as a bug.

**Comment by vakhtang** [comment]
Could you provide a repo I could clone to troubleshoot this?

**Comment by Secretmapper** [comment]
Also reporting that the same error appears on non-RN projects (straight up server pre-rendered React projects using webpack).

I'll see if I can provide a small repo later today.

**Comment by Secretmapper** [comment]
Sample repo:

https://github.com/Secretmapper/victory-sample

**Comment by Secretmapper** [comment]
Just tagging @vakhtang :)

**Comment by vakhtang** [comment]
Thanks @Secretmapper. I'll take a look today!

**Comment by boygirl** [comment]
@Secretmapper can you give this a shot with `victory-chart-native` and / or `victory-pie-native` as your dependencies instead of relying on the main Victory packages?
