### ISSUE TITLE
tickCount not working properly

### ISSUE THREAD

**Issue by chilijung** [FormidableLabs/victory-chart#287]
I'm trying to set many date data in x axis and found out ticks squeeze together.  And I tried to set `tickCount` props according to the docs it should `specifies approximately how many ticks should be drawn on the axis` but not working.

![2016-07-07 9 45 48](https://cloud.githubusercontent.com/assets/1216029/16655395/b20f6840-448c-11e6-8810-8b110fc912d6.png)

```jsx
       <VictoryAxis
          scale="time"
          tickValues={<many date data>}
          tickCount={5}
          tickFormat={x => `${x.getMonth() + 1}/${x.getDate()}`}
          style={{
            data: {
              strokeWidth: 2
            },
            labels: {
              fontSize: 16
            }
          }}
          orientation="bottom"
          standalone={false}
        />

```

![2016-07-07 9 44 04](https://cloud.githubusercontent.com/assets/1216029/16655261/1fa3af2a-448c-11e6-94a9-54308579a4f6.png)

is it a bug? or I'm doing something wrong?

**Comment by boygirl** [comment]
@chilijung If you are specifying `tickValues` the `tickCount` prop wont do anything. It is used when creating a set of default ticks
