### ISSUE TITLE
How to set baseline style in bar chart

### ISSUE THREAD

**Issue by chilijung** [FormidableLabs/victory-chart#292]
I've a bar chart with both positive and negative value, and I want to show a baseline in 0. thanks.

![2016-07-11 12 39 38](https://cloud.githubusercontent.com/assets/1216029/16720033/9b78d8ac-4764-11e6-8b8f-a429e0165069.png)

**Comment by ebrillhart** [comment]
@chilijung do you want to keep the current x-axis at the bottom of the chart and add an additional axis at zero, or shift the axis to be at the zero point?
