### ISSUE TITLE
label position wrong in orientation right

### ISSUE THREAD

**Issue by chilijung** [FormidableLabs/victory-chart#293]
The position of the label will be wrong (won't show up in the chart, it will be outside svg container.)when the orientation of the axis set to right.

![2016-07-11 1 03 58](https://cloud.githubusercontent.com/assets/1216029/16720354/16ca6978-4768-11e6-8a3b-daff4d9702de.png)

**Comment by ebrillhart** [comment]
hi @chilijung! this is a known issue that we are currently working on fixing. thank you for the heads up!
