### ISSUE TITLE
calculate bar width

### ISSUE THREAD

**Issue by chilijung** [FormidableLabs/victory-chart#294]
When using bar chart in charts. The width is only a fixed value right now, and it won't look great in most chart.

![2016-07-11 12 39 38](https://cloud.githubusercontent.com/assets/1216029/16720386/65cdccd6-4768-11e6-8ba4-5844c59d045a.png)

render in a more better width.

![2016-07-11 1 06 30](https://cloud.githubusercontent.com/assets/1216029/16720388/6d683008-4768-11e6-8214-07856ac81c1f.png)

Maybe it should calculate a fit width size by it's own, would be really convenience when the data is dynamic.

BTW, how could I set to make my bar chart fit in the chart. In the example above the rightmost bar didn't fit in the chart.

**Comment by ebrillhart** [comment]
@chilijung the dynamic width for bar charts is upcoming! It's already merged to master and will be out in the next release. For the width issue in your second chart, you can set the domain to be larger via the domain prop, or you can use the domainPadding prop on VictoryChart if that's a component that you're including.
