### ISSUE TITLE
Add domainPadding or equivalent to VictoryAxis?

### ISSUE THREAD

**Issue by ebrillhart** [FormidableLabs/victory-chart#295]
Might be useful to be able to add domain padding even when not using the full VictoryChart wrapper.

**Comment by boygirl** [comment]
@ebrillhart, @angelanicholas and I have discussed supporting the `domainPadding` prop on all of the individual components. Do you feel confident taking on this task?

**Comment by ebrillhart** [comment]
@boygirl yep I'll start looking into this!

**Comment by ebrillhart** [comment]
closed with https://github.com/FormidableLabs/victory-chart/pull/303
