### ISSUE TITLE
VictoryChart breaks with log scale

### ISSUE THREAD

**Issue by ebrillhart** [FormidableLabs/victory-chart#299]
Breaks on all chart types, even if the child chart component by itself displays fine with a log scale. Fairly sure it has to do with an issue rendering the axes

**Comment by boygirl** [comment]
@ebrillhart maybe check on how VictoryAxis is calculating its automatic tickValues (you might check first whether it breaks when you provide tickValues for the axis). This problem will pop up somewhere that `scale()` is being used. That's my best guess.

**Comment by ebrillhart** [comment]
@boygirl just so the info is all in one place, I've found the following:
axis handles log scale fine UNLESS it's wrapped or not standalone and doesn't have a specified domain (without zero or negative numbers) or specified tickValues. so it's something specifically about how chart processes the axis (probably because there's a zero in the domain added?) that I'll continue to dig into.

**Comment by boygirl** [comment]
@ebrillhart VictoryChart will try to create `tickValues` for its axes. I would start with whatever method is doing that in VictoryChart helpers

**Comment by ebrillhart** [comment]
mostly fixed with https://github.com/FormidableLabs/victory-chart/pull/317#issuecomment-235330240 and closing in favor of #320
