### ISSUE TITLE
Axis domain doesn't work(or useless) on victory area without area domain 

### ISSUE THREAD

**Issue by nightwolfdu** [FormidableLabs/victory-chart#305]
Hello,
I found some strange behaviour with VictoryArea & VictoryAxis.
VictoryAxis "domain" property
has no effect on VictoryArea bottom side
![image](https://cloud.githubusercontent.com/assets/5007467/16984755/cdac7988-4e84-11e6-9b47-045b67732d7b.png)
Here is a code sample: https://jsfiddle.net/6b8h7tqx/
Is it expected?

**Comment by dandelany** [comment]
Hi! In an area chart, the *area* under the line is the meaningful value - therefore the Y-axis *must* include zero, and VictoryArea correctly enforces this best practice. If you need a truncated Y-axis, I recommend using a line chart.

**Comment by boygirl** [comment]
@nightwolfdu or if you do need a different domain, you should set it directly on VictoryChart. Otherwise, the domain will include the maximum extent of all the combined child domains (which, as @dandelany said will include zero for VictoryArea)
