### ISSUE TITLE
When a theme is specified on a wrapper, children cant specify their own colorScale

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-chart#329]
Prefer `colorScale` in `child.props` over theme `colorScale`

**Comment by ebrillhart** [comment]
I'm a little confused, because right now only the group and stack wrappers even accept a colorScale prop? I couldn't apply a colorscale to a child component and have it show up even if there isn't a theme applied. or should that also be fixed

**Comment by boygirl** [comment]
If you have a theme on `VictoryChart` and you try to specify a `colorScale` on a `VictoryStack` nested inside chart, the `colorScale` prop will be ignored
