### ISSUE TITLE
Specifying tickValues moves ticks out of view on the right

### ISSUE THREAD

**Issue by chielkunkels** [FormidableLabs/victory-chart#334]
First off, thanks for the awesome library. Just found it and started using it and it's working a treat.

However, when I specify the `tickValues` on a `VictoryAxis` component, the ticks somehow move all the way off to the right:
![screen shot 2016-08-08 at 14 01 35](https://cloud.githubusercontent.com/assets/141643/17479116/cd63972c-5d70-11e6-8c1c-b7610ac48486.png)

If I don't specify `tickValues` everything renders as you'd expect:
![screen shot 2016-08-08 at 14 03 38](https://cloud.githubusercontent.com/assets/141643/17479145/fdf8fb84-5d70-11e6-887e-00447d4ac7d4.png)

As you can see this doesn't look too great. Am I missing something, or is this a bug?

Thanks again for the great library!

**Comment by boygirl** [comment]
@chielkunkels I haven't seen this exact bug before, but we've had some persistent confusion between `tickValues` and `tickFormat`. I think what you want here is probably `tickFormat={(tick) => tick.getDate() + "/" + tick.getMonth() +1}`

**Comment by chielkunkels** [comment]
@boygirl I did look at `tickFormat` first actually, but for some reason the incoming value there was just an integer, going from `1` to `14`, rather than the actual date string that I had, so that seems to be another issue (maybe also related to my code - unsure).

As for the code, with `tickValues`:

```jsx
<VictoryChart
	width={856}
	height={352}
	padding={{ top: 0, left: 50, right: 0, bottom: 30 }}
	domainPadding={{ x: 20, y: 20 }}
>
	<VictoryAxis
		style={{ ticks: { size: 5, stroke: '#000', strokeWidth: 1 } }}
		tickValues={weight.map(tick => moment(tick.date).format('D/M'))}
	/>
	<VictoryAxis
		dependentAxis
		style={{ grid: { stroke: '#eee' } }}
		tickFormat={y => parseInt(y, 10)}
	/>
	<VictoryLine
		interpolation="cardinal"
		data={weight}
		x="date"
		y="weight"
		style={{ data: { stroke: '#ff4081' } }}
	/>
	<VictoryScatter
		data={weight}
		x="date"
		y="weight"
		size={5}
		style={{ data: { fill: '#444', stroke: 'white', strokeWidth: 5 } }}
	/>
</VictoryChart>
```

Where `weight` is an array of objects shaped like:

```js
const weight = [
	{
		date: '2016-08-08',
		weight: 106.9
	},
	...
];
```

Let me know if you need more information regarding this issue!

Cheers.

**Comment by boygirl** [comment]
Ah, so two things are going on... your date value is coming in as a string, to get actual dates you can set your `x` data accessor to `x={(w) => new Date(w.date)}` or something. Then you should also set a `scale` prop on `VictoryChart` like `scale={{x: "time"}}`. We're working on making this second step automatic.

**Comment by chielkunkels** [comment]
Ah sweet. Thanks for the help, that seems to have done the trick. However, I am still a bit confused since I thought that `tickFormat` would simply pass whatever the value would be. Is this because it was not a number or a date?

One other thing I am having now, is that it renders every other date - is there also a way to control that?

Thanks again!

**Comment by boygirl** [comment]
To support categorical data we end up mapping string values to integers starting at 1 and just using a linear scale. That's why you were getting `[1, 2, ...14]`. If you need specific dates as ticks you can try one of the following depending on what works best for you

1) specify the `tickValues` prop as an array of Date objects, and specify a function for `tickFormat` that will operate on each tick

2) leave `tickValues` unspecified and pass a `tickCount` prop and continue specifying a function for `tickFormat` that will operate on each tick. This solution will let the same axes work for different data, but be aware that the `tickCount` prop can only approximate the number of ticks that will actually show up, because `d3Scale.tick` prioritizes evenly spaced ticks with "nice" values over an exact number.

**Comment by chielkunkels** [comment]
Alright excellent - thank you so much for the explanation, it makes a lot of sense now. It's still weird that it moved the thing over to the right before though, but oh well.

I'll have a look at how I can get the exact dates, I think option 1 makes the most sense in that regard.

Thanks again!
