### ISSUE TITLE
1px of space between stacked bars

### ISSUE THREAD

**Issue by angelanicholas** [FormidableLabs/victory-chart#350]
very subtle but you can see 1px of the dark blue bars in the background peaking through between the overlaid stacked bar:

<img width="171" alt="screen shot 2016-08-17 at 12 25 52 pm" src="https://cloud.githubusercontent.com/assets/2624467/17750179/d01c6280-6475-11e6-891a-52ecb351791e.png">

**Comment by boygirl** [comment]
This issue was moved to FormidableLabs/victory#345
