### ISSUE TITLE
two perf improvements related with labels

### ISSUE THREAD

**Issue by nfcampos** [FormidableLabs/victory-chart#351]
Here goes:
- in https://github.com/FormidableLabs/victory-chart/blob/master/src/components/victory-scatter/helper-methods.js#L79 this would shortcircuit and be faster when `datum.label` exists
```js
return datum.label || Array.isArray(props.labels) ?
  props.labels[index] : Helpers.evaluateProp(props.labels, datum);
```

- in https://github.com/FormidableLabs/victory-chart/blob/master/src/components/victory-scatter/helper-methods.js#L27 the label stuff below this line can be skipped `if (!text && !props.events)` this is actually relevant to performance because the time spent in `getLabelStyle` is not insignificant (in my benchmarks at least)

These two things probably apply to all the other chart types. what do you guys think?

**Comment by boygirl** [comment]
@nfcampos thanks for catching these. Both look like changes we should make.
