### ISSUE TITLE
tick parser function for doing custom integers

### ISSUE THREAD

**Issue by colinmegill** [FormidableLabs/victory-chart#45]
We have d3's format for dates, but something like http://numeraljs.com/ might be the right thing for integers. 6k minified.

**Comment by colinmegill** [comment]
We expose tick values, so theoretically the user could do this on the client. I think the use case is, like date, where you are given a domain and the tick values are automatically spaced / generated, but you want them to have a specific format.

**Comment by boygirl** [comment]
already implemented as `tickFormat` takes a function.
