### ISSUE TITLE
Improve loading experience in static docs site

### ISSUE THREAD

**Issue by david-davidson** [FormidableLabs/victory-chart#52]
http://projects.formidablelabs.com/victory-chart/

Before the JS bundle loads, the server-rendered bullets are broken!

Blocks launch of main lander.

**Comment by boygirl** [comment]
Playgrounds also load slow, but since they show up as regular markdown code block on load it looks a little less broken. Still.. getting those to load as playgrounds the first time would be awesome

**Comment by david-davidson** [comment]
@boygirl Roger that, agreed.
