### ISSUE TITLE
Recursively check descendants for static `getDomain` method.

### ISSUE THREAD

**Issue by dandelany** [FormidableLabs/victory-chart#94]
The Victory chart types (line, bar, etc.) all implement a static `getDomain` method which allows `VictoryChart` to ‘ask’ all of its children what their data domains are, and combine them to determine the overall domains for the x and y axes. However, as noted by @mathisonian in the chat room, this means that if someone writes a thin wrapper component around, say, `VictoryLine`, and tries to render this wrapper inside of a `VictoryChart`, it will cause an error due to the wrapper component not having a `getDomain` static method.

We should look into handling this better automatically… Ie. if a `VictoryChart` child doesn’t have a getDomain method, we could probably recursively check if its `child.props.children` do, and use them instead.

**Comment by mathisonian** [comment]
I'd be very happy to see something like this, or even just an example of the proper way to handle adding a `getDomain` method to the custom component.

Let me know if there's anything I can do to help.

**Comment by okonet** [comment]
+1

**Comment by boygirl** [comment]
From the gitter channel 

@alikhani: Adding VictoryLabel to the VictoryChart throws an Uncaught TypeError: component.type.getDomain is not a function.

Chart should be able to ignore children that do not have or need a `getDomain` method when calculating domain
