### ISSUE TITLE
Increase labelComponent api consistency between VictoryScatter and VictoryBar

### ISSUE THREAD

**Issue by cpb** [FormidableLabs/victory-chart#96]
During the documentation effort in https://github.com/FormidableLabs/victory-chart/pull/95 I noticed some discrepancies between ```VictoryScatter``` and ```VictoryBar``` ```labelComponent``` (or ```labelComponents```) properties.

- Whereas ```VictoryBar``` provides defaults, ```VictoryScatter``` enforces its styles. Can we align these two charts' label style strategies? 
- Whereas ```VictoryScatter``` uses ```React.cloneElement``` on a single element, ```VictoryBar``` uses an array, and clones each element. Given the datum for the ```Point``` or ```Bar``` includes the ```label``` text, can we favour the ```VictoryScatter``` interface of a single ```labelComponent``` to the ```VictoryBar``` interface of an array of ```labelComponent```? In the use case for providing custom elements for category labels, at least the ```<VictoryBar />``` statement would include less repetition.

If you like those two suggestions, I'll go ahead and make a pull request to:

- [x] Make the label style merging the same between ```VictoryBar``` and ```VictoryScatter```
- [x] Provide a deprecation warning for the ```labelComponents``` property.
- [x] Implement a ```labelComponent``` property for ```VictoryBar``` that matches ```VictoryScatter``` ```labelComponent``` property.
- [x] Update the documentation for each property.

**Comment by boygirl** [comment]
@cpb, I think we can do away with `labelComponents` in favor of `labelComponent` in VictoryBar, so long as we keep the `labels` array prop.

**Comment by cpb** [comment]
@boygirl should I use the "new" ```deprecated``` validator to help this transition? ;-)

And what about the label style merging behaviour differences?

**Comment by boygirl** [comment]
@cpb prefer defaults to enforced style. Thanks for catching these differences

**Comment by cpb** [comment]
#98 solves this, just waiting for merge :-)

**Comment by boygirl** [comment]
Closed by #98
